version: '3.8'

services:
  server:
    image: python:flask
    volumes:
      - ${PWD}/src:/app
      - ${PWD}/logs:/app/logs
      - ${PWD}/pickles:/app/pickles
    working_dir: /app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 3
    entrypoint: /bin/sh
    command: -c 'flask run -h 0.0.0.0 -p 3000'

  log_reader:
    image: python:flask
    volumes:
      - ${PWD}/src:/app
      - ${PWD}/logs:/app/logs
      - ${PWD}/pickles:/app/pickles
    working_dir: /app
    depends_on:
      server:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c 'while true; do python log_reader_cron.py; sleep 30; done'
